% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Jul-2024 07:08:06
%  MATLAB version: 9.13.0.2502115 (R2022b) Update 8
% -------------------------------------------------------------------
                                                                    

C_stopLightsSpeedThresholdSafety = Simulink.Parameter;
C_stopLightsSpeedThresholdSafety.Value = 3;
C_stopLightsSpeedThresholdSafety.Complexity = 'real';
C_stopLightsSpeedThresholdSafety.HasCoderInfo = false;
C_stopLightsSpeedThresholdSafety.Description = '';
C_stopLightsSpeedThresholdSafety.DataType = 'uint8';
C_stopLightsSpeedThresholdSafety.Min = 0;
C_stopLightsSpeedThresholdSafety.Max = 100;
C_stopLightsSpeedThresholdSafety.DocUnits = 'km/h';

