% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Jul-2024 07:21:10
%  MATLAB version: 9.13.0.2502115 (R2022b) Update 8
% -------------------------------------------------------------------
                                                          

VehicleSpeedAbsoluteValueT = Simulink.AliasType;
VehicleSpeedAbsoluteValueT.Description = '';
VehicleSpeedAbsoluteValueT.DataScope = 'Auto';
VehicleSpeedAbsoluteValueT.HeaderFile = 'Rte_Type.h';
VehicleSpeedAbsoluteValueT.BaseType = 'single';


type_StopLightsEvent_usageId = Simulink.AliasType;
type_StopLightsEvent_usageId.Description = '';
type_StopLightsEvent_usageId.DataScope = 'Auto';
type_StopLightsEvent_usageId.HeaderFile = 'Rte_Type.h';
type_StopLightsEvent_usageId.BaseType = 'uint8';


type_StopLightsFailureAlertEvent_occurrence = Simulink.AliasType;
type_StopLightsFailureAlertEvent_occurrence.Description = '';
type_StopLightsFailureAlertEvent_occurrence.DataScope = 'Auto';
type_StopLightsFailureAlertEvent_occurrence.HeaderFile = 'Rte_Type.h';
type_StopLightsFailureAlertEvent_occurrence.BaseType = 'uint8';


type_setStopLightsASILB_usageId = Simulink.AliasType;
type_setStopLightsASILB_usageId.Description = '';
type_setStopLightsASILB_usageId.DataScope = 'Auto';
type_setStopLightsASILB_usageId.HeaderFile = 'Rte_Type.h';
type_setStopLightsASILB_usageId.BaseType = 'uint8';


type_setStopLightsIOControl_usageId = Simulink.AliasType;
type_setStopLightsIOControl_usageId.Description = '';
type_setStopLightsIOControl_usageId.DataScope = 'Auto';
type_setStopLightsIOControl_usageId.HeaderFile = 'Rte_Type.h';
type_setStopLightsIOControl_usageId.BaseType = 'uint8';


type_setStopLightsWarningQM_usageId = Simulink.AliasType;
type_setStopLightsWarningQM_usageId.Description = '';
type_setStopLightsWarningQM_usageId.DataScope = 'Auto';
type_setStopLightsWarningQM_usageId.HeaderFile = 'Rte_Type.h';
type_setStopLightsWarningQM_usageId.BaseType = 'uint8';

