% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Jul-2024 07:08:06
%  MATLAB version: 9.13.0.2502115 (R2022b) Update 8
% -------------------------------------------------------------------
                                                                   

VehicleSpeedAbsoluteValueT = Simulink.AliasType;
VehicleSpeedAbsoluteValueT.Description = '';
VehicleSpeedAbsoluteValueT.DataScope = 'Auto';
VehicleSpeedAbsoluteValueT.HeaderFile = 'Rte_Type.h';
VehicleSpeedAbsoluteValueT.BaseType = 'single';


type_setStopLightsASILB_usageId = Simulink.AliasType;
type_setStopLightsASILB_usageId.Description = '';
type_setStopLightsASILB_usageId.DataScope = 'Auto';
type_setStopLightsASILB_usageId.HeaderFile = 'Rte_Type.h';
type_setStopLightsASILB_usageId.BaseType = 'uint8';
