Simulink.defineIntEnumType( 'CANBrakePedalPressedByDriver', ...
   {'CANBRAKEPEDALPRESSEDBYDRIVER_NOT_PRESSED','CANBRAKEPEDALPRESSEDBYDRIVER_PRESSED','CANBRAKEPEDALPRESSEDBYDRIVER_UNAVAILABLE','CANBRAKEPEDALPRESSEDBYDRIVER_NOT_USED'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'CANBRAKEPEDALPRESSEDBYDRIVER_NOT_PRESSED', ...
   'StorageType', 'uint8', ...
   'DataScope', 'Auto' , ...   
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CANESPStopLampRequest', ...
   {'CANESPSTOPLAMPREQUEST_NOT_REQUESTED','CANESPSTOPLAMPREQUEST_ON_REQUESTED'}, ...
   [1 2], ...
   'DefaultValue', 'CANESPSTOPLAMPREQUEST_NOT_REQUESTED', ...
   'StorageType', 'uint8', ...
   'DataScope', 'Auto' , ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CANHEVCStopLampRequest', ...
   {'CANHEVCSTOPLAMPREQUEST_OFF_REQUEST','CANHEVCSTOPLAMPREQUEST_ON_REQUEST'}, ...
   [1 2], ...
   'DefaultValue', 'CANHEVCSTOPLAMPREQUEST_OFF_REQUEST', ...
   'StorageType', 'uint8', ...
   'DataScope', 'Auto' , ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SpeedSignT', ...
   {'SPEED_SIGN_T_NULL_SPEED_OR_LESS_THAN_MIN_DETECTABLE','SPEED_SIGN_T_POSITIVE_VEHICLE_SPEED_FORWARD_MOTION','SPEED_SIGN_T_NEGATIVE_VEHICLE_SPEED_REVERSE_MOTION','SPEED_SIGN_T_UNAVAILABLE'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SPEED_SIGN_T_NULL_SPEED_OR_LESS_THAN_MIN_DETECTABLE', ...
   'StorageType', 'uint8', ...
   'DataScope', 'Auto' , ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SpeedSupposedStateT', ...
   {'SPEEDSUPPOSEDSTATE_STANDSTILL','SPEEDSUPPOSEDSTATE_UNAVAILABLE','SPEEDSUPPOSEDSTATE_MOVING'}, ...
   [1 0 2], ...
   'DefaultValue', 'SPEEDSUPPOSEDSTATE_STANDSTILL', ...
   'StorageType', 'uint8', ...
   'DataScope', 'Auto' , ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'StopLightsPatternID', ...
   {'STOP_LIGHTS_PATTERN_ID_OFF','STOP_LIGHTS_PATTERN_ID_ON','STOP_LIGHTS_PATTERN_ID_WARNING'}, ...
   [0 1 2], ...
   'DefaultValue', 'STOP_LIGHTS_PATTERN_ID_OFF', ...
   'StorageType', 'uint8', ...
   'DataScope', 'Auto' , ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'UsageAction', ...
   {'USAGEACTION_IMPULSE_COMMAND','USAGEACTION_OPEN_SESSION','USAGEACTION_CLOSE_SESSION'}, ...
   [0 1 2], ...
   'DefaultValue', 'USAGEACTION_IMPULSE_COMMAND', ...
   'StorageType', 'uint8', ...
   'DataScope', 'Auto' , ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'ValueState', ...
   {'VALUE_STATE_UNAVAILABLE','VALUE_STATE_INVALID','VALUE_STATE_VALID'}, ...
   [0 2 1], ...
   'DefaultValue', 'VALUE_STATE_UNAVAILABLE', ...
   'StorageType', 'uint8', ...
   'DataScope', 'Auto' , ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'VehiclePowerModeType', ...
   {'VEHICLEPOWERMODE_LOW_POWER','VEHICLEPOWERMODE_PARK','VEHICLEPOWERMODE_SW_UPDATE','VEHICLEPOWERMODE_LIFE_ON_BOARD','VEHICLEPOWERMODE_POWER_ON','VEHICLEPOWERMODE_TRACTION_ON','VEHICLEPOWERMODE_UNDEFINED','VEHICLEPOWERMODE_NOT_USED'}, ...
   [0 1 2 3 4 5 7 6], ...
   'DefaultValue', 'VEHICLEPOWERMODE_LOW_POWER', ...
   'StorageType', 'uint8', ...
   'DataScope', 'Auto' , ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

